// 前端错误类型
export const JS_TRACKER_ERROR_MAP = {
  ERROR_CUSTOM: 0,
  ERROR_RUNTIME: 1,
  ERROR_SCRIPT: 2,
  ERROR_STYLE: 3,
  ERROR_IMAGE: 4,
  ERROR_AUDIO: 5,
  ERROR_VIDEO: 6,
  ERROR_PROMISE: 7,
  ERROR_HTTP: 8,
}

// 资源加载错误
export const LOAD_ERROR_TYPE = {
  SCRIPT: JS_TRACKER_ERROR_MAP.ERROR_SCRIPT,
  LINK: JS_TRACKER_ERROR_MAP.ERROR_STYLE,
  IMG: JS_TRACKER_ERROR_MAP.ERROR_IMAGE,
  AUDIO: JS_TRACKER_ERROR_MAP.ERROR_AUDIO,
  VIDEO: JS_TRACKER_ERROR_MAP.ERROR_VIDEO,
}
